### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ghost** [dtalens/nginx-naxsi-deb#1]
Hi,

Can you publish debian source package and instructions how you build it?

There were some new PRs, changes to Naxsi. It would be great to have an updated deb package for it. 

Thanks,

**Comment by dtalens** [comment]
Hello,

In this [post](https://dtalens.com/2019/11/09/com-augmentar-la-seguretat-dun-servidor-nginx-en-ubuntu-18-04/) I explain how I created the debian package from the nginx and naxsi source code. The _configure_ options are the same as the deb package in the official nginx repository.

Currently I do not use naxsi as it produces many false positives on my websites. I use nemesida WAF which generates less false positives although I don't like that it is not GNU.
